services:
  - type: web
    name: clarity-ai-backend
    runtime: docker
    plan: starter
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false